name: analytic
on:
  push:
    branches: [ "main" ]
    paths:
      - 'analytic/__**'
      - 'analytic/main.py'
      - 'analytic/everon.py'
  pull_request:
    # branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  analytic:
    runs-on: ubuntu-latest
    # runs-on: ${{matrix.operating-system}}
    
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     # operating-system: [ubuntu-latest]
    #     operating-system: [ubuntu-latest, debian12x64, debian11x64]

    steps:
      - run: sudo timedatectl set-timezone Asia/Ho_Chi_Minh
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          cache: 'pip'
      - run: bash .github/ci/requirements.sh
      - run: |
          sudo killall firefox 2>/dev/null || true
          sudo killall google-chrome 2>/dev/null || true
          sudo killall chrome 2>/dev/null || true
          python -u analytic || true
        shell: bash
        env:
          MODE: product
          TYPE: everon
      - name: Setup GPG
        uses: diepxuan/.github/.github/actions/gpg-setup@main
        with:
          gpg_key: ${{ secrets.GPG_KEY }}
          gpg_key_id: ${{ secrets.GPG_KEY_ID }}
          committer_email: ${{ secrets.GIT_COMMITTER_EMAIL }}
          committer_name: ${{ github.repository_owner }}
      - name: Push repository
        run: |
          if [ "$(git status images/ --porcelain=v1 2>/dev/null | wc -l)" != "0" ]; then
            # git checkout -b ci
            git add images/
            git commit -m "CI images update"
            # git commit -m "Update images at $(date +'%d-%m-%y')"
            git fetch -ap
            # git branch --set-upstream-to origin/ci ci
            git pull --rebase -X ours
            # git push origin HEAD:ci
            git push origin HEAD:main
          fi
