name: facebook
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  facebook:
    runs-on: ubuntu-latest
    # runs-on: ${{matrix.operating-system}}
    strategy:
      fail-fast: false
      # matrix:
        # operating-system: [ubuntu-22.04, ubuntu-20.04]
    steps:
      - run: sudo timedatectl set-timezone Asia/Ho_Chi_Minh
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          cache: 'pip'
      # - run: bash .github/ci/requirements.sh
      - run: bash .github/ci/facebook.sh
        env:
          DB_HOST: mysql.diepxuan.corp
          DB_DATABASE: n8n
          DB_USERNAME: n8n
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: 3306
          TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
