name: images
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "analytic.md"
  pull_request:
    # branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "30 */6 * * *"

jobs:
  images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "$GPG_KEY====" | tr -d '\n' | fold -w 4 | sed '$ d' | tr -d '\n' | fold -w 76 | base64 -di | gpg --batch --import || true
          gpg --list-secret-keys --keyid-format=long
          git config user.email "$GIT_COMMITTER_EMAIL"
          git config user.name "$GIT_COMMITTER_NAME"
          git config commit.gpgsign true
          git config user.signingkey $GPG_KEY_ID
        env:
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ github.repository_owner }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          cache: 'pip'
      - run: bash .github/ci/nameservers.sh
        if: false
      - run: bash .github/ci/requirements.sh
      - run: bash .github/ci/images.sh
      - name: Push repository
        if: true
        run: |
          if [ "$(git status --porcelain=v1 2>/dev/null | wc -l)" != "0" ]; then
            git add images/
            git commit -m "Update dists at $(date +'%d-%m-%y')"
            # git push https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
            # git push
            git stash
            git pull --rebase
            git stash apply
            # git push https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
            git push
          fi